# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 5, 12, 10, 42, 52, 895000), null=True),
        ),
    ]
