# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0005_auto_20180607_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 7, 13, 25, 49, 864802), null=True),
        ),
    ]
