# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0007_auto_20180627_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='hitlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 27, 10, 1, 37, 313200), null=True),
        ),
    ]
