# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 10:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0009_auto_20180627_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 27, 10, 17, 36, 743200), null=True),
        ),
    ]
