# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0010_auto_20180627_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InerterestLog',
            new_name='InterestLog',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 27, 10, 44, 53, 794200), null=True),
        ),
    ]
