# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0012_auto_20180701_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('month', models.CharField(blank=True, max_length=2, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='', null=True, upload_to='uploads/user/service')),
                ('intro', models.TextField()),
                ('file', models.FileField(blank=True, default='', null=True, upload_to='uploads/user/service')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Startup')),
            ],
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 1, 21, 18, 31, 91001), null=True),
        ),
    ]
