# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 16:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0015_auto_20180701_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 2, 16, 27, 44, 215001), null=True),
        ),
    ]
