# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 15:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0025_auto_20180703_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='pick_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 4, 15, 38, 15, 578001), null=True),
        ),
    ]
