# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 19:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0028_auto_20180704_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='back_img',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='logo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 8, 19, 15, 15, 299000), null=True),
        ),
    ]
