# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 09:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0030_auto_20180710_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 11, 9, 9, 32, 311000), null=True),
        ),
    ]
