# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0034_auto_20180712_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 12, 17, 6, 0, 746400), null=True),
        ),
    ]
