# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0038_auto_20180712_1836'),
    ]

    operations = [
        migrations.RenameField(
            model_name='path',
            old_name='object',
            new_name='rec_dur',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 12, 19, 13, 34, 500400), null=True),
        ),
    ]
