# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 01:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0046_auto_20180715_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='HitClipLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HitCourseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HitPathLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WatchClipHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WatchCourseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='WatchPathHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Path')),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='watchlog',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='watchlog',
            name='course',
        ),
        migrations.RemoveField(
            model_name='watchlog',
            name='path',
        ),
        migrations.RemoveField(
            model_name='watchlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 17, 1, 18, 9, 795800), null=True),
        ),
        migrations.DeleteModel(
            name='WatchLog',
        ),
    ]
