# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 02:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0047_auto_20180717_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchcoursehistory',
            name='clip',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 17, 2, 7, 27, 324800), null=True),
        ),
    ]
