# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0052_auto_20180719_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='additional_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 19, 9, 50, 59, 134800), null=True),
        ),
    ]
