# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='open_date',
            field=models.DateField(default='2018-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
