# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0005_auto_20180214_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='createdate',
            field=models.DateField(default='2017-01-01'),
            preserve_default=False,
        ),
    ]
