# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0006_supportbusiness_createdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='apply_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
