# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0012_auto_20180225_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='keyword',
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='service_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(to='supporting_business.Tag'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
