# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0015_startup_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='startup',
            old_name='fund_status',
            new_name='short_desc',
        ),
    ]
