# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0016_auto_20180227_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='fund_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
