# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0021_auto_20180227_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='belong_to',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='department',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
