# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0028_auto_20180302_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_0_choose_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_0_criterion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_0_criterion_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_0_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_0_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_choose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_choose_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_criterion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_criterion_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_1_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_choose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_choose_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_criterion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_criterion_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='pro_2_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='supply_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='supply_condition_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='supply_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='supply_content_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
