# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0031_auto_20180302_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusiness',
            name='created_at',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
