# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0032_auto_20180302_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportbusiness',
            old_name='meta_data',
            new_name='meta',
        ),
    ]
