# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0033_auto_20180302_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appliance',
            name='sb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness'),
        ),
    ]
