# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0038_auto_20180303_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='kind2_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='meta_file_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
