# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0039_auto_20180303_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='keyword',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
