# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0043_auto_20180305_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliance',
            name='address',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='assurance_employ',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='business_number',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='design',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='facebook_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='fund_before_0',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='fund_before_1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='fund_before_2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='hold_employ',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='industry_category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='insta_address',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='intro',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='keyword',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='mark_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='mark_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='mark_tel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='oversea',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='oversea_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='patent',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='patent_2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='repre_email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='repre_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='repre_tel',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='revenue_before_0',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='revenue_before_1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='revenue_before_2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='service_category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='service_intro',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='specification',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='total_employ',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='trademark',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='additional_faq',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='business_detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='business_detail_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='choose_method',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='condition',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='condition_etc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='condition_etc_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='condition_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='constraint',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='constraint_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='etc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='etc_file_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='faq',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='faq_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='icon_set',
            field=models.CharField(blank=True, default='', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='kind2_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='meta',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='meta_file_info',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='object',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='object_span',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='object_span_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='object_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='place',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='place_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='prefer',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='prefer_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_0_choose',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_0_choose_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_0_criterion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_0_criterion_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_1_choose',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_1_choose_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_1_criterion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_1_criterion_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_2_choose',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_2_choose_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_2_criterion',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='pro_2_criterion_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='recruit_size',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='subject',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='subject_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='supply_condition',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='supply_condition_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='supply_content',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='supply_content_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='title',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='title_sub',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='title_sub_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='title_tag',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
