# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0048_auto_20180306_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='address',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
