# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0049_auto_20180306_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='filter',
            field=models.ManyToManyField(to='supporting_business.Filter'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='interest',
            field=models.ManyToManyField(to='supporting_business.SupportBusiness'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(to='supporting_business.Tag'),
        ),
    ]
