# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0050_auto_20180306_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startup',
            name='interest',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='interest',
            field=models.ManyToManyField(to='supporting_business.SupportBusiness'),
        ),
    ]
