# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0051_auto_20180307_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusiness',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
