# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0052_auto_20180308_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='short_desc',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
    ]
