# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-14 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0062_auto_20180314_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='export_before_0',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='export_before_1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='export_before_2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
