# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0067_auto_20180318_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_9',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
