# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0070_additionaluserinfo_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_9',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
    ]
