# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0072_supportbusiness_is_blind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvgTimePerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='DayUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='ExpireTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='PagePerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.CreateModel(
            name='SessionPerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=None, default=0, null=None)),
            ],
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
