# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0075_hitlog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailConirmation',
            new_name='EmailConfirmation',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 3, 24, 13, 19, 21, 57414), null=True),
        ),
    ]
