# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-05 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0079_auto_20180329_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='confirm_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 5, 21, 56, 59, 681403), null=True),
        ),
    ]
