# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0080_auto_20180405_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 6, 1, 14, 1, 249403), null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='confirm_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
