# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0081_auto_20180406_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 6, 1, 14, 4, 226403), null=True),
        ),
    ]
