# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0002_quatertablesupportbusiness'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quatertablesupportbusiness',
            name='support_business_author',
        ),
        migrations.DeleteModel(
            name='QuaterTableSupportBusiness',
        ),
    ]
