# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-07 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0003_auto_20180607_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='startup_found_gg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 7, 13, 6, 22, 510802), null=True),
        ),
    ]
