# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0004_quatertablesupportbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='quatertablesupportbusiness',
            name='support_business',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quatertablesupportbusiness',
            name='support_business_approved_date_ymd',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quatertablesupportbusiness',
            name='support_business_status',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
