# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 09:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0006_auto_20180607_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='InerterestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('up_down', models.IntegerField(max_length=1)),
                ('sb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 6, 27, 9, 59, 5, 608200), null=True),
        ),
    ]
