# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0008_auto_20180926_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quatertablesupportbusiness',
            old_name='support_business',
            new_name='qt_support_business',
        ),
        migrations.RenameField(
            model_name='quatertablesupportbusiness',
            old_name='support_business_approved_date_ymd',
            new_name='qt_support_business_approved_date_ymd',
        ),
        migrations.RenameField(
            model_name='quatertablesupportbusiness',
            old_name='support_business_author',
            new_name='qt_support_business_author',
        ),
        migrations.RenameField(
            model_name='quatertablesupportbusiness',
            old_name='support_business_status',
            new_name='qt_support_business_status',
        ),
    ]
