# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 03:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0009_auto_20180926_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredchannel',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
