# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-02 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0010_registeredchannel_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritecliplog',
            name='favorite_clip',
        ),
        migrations.RemoveField(
            model_name='favoritecliplog',
            name='favorite_user',
        ),
        migrations.RemoveField(
            model_name='favoritecourselog',
            name='favorite_course',
        ),
        migrations.RemoveField(
            model_name='favoritecourselog',
            name='favorite_user',
        ),
        migrations.RemoveField(
            model_name='favoritepathlog',
            name='favorite_path',
        ),
        migrations.RemoveField(
            model_name='favoritepathlog',
            name='favorite_user',
        ),
        migrations.AlterModelOptions(
            name='additionaluserinfo',
            options={'verbose_name': '회원 관리', 'verbose_name_plural': '회원 관리'},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'verbose_name': '스타트업 관리', 'verbose_name_plural': '스타트업 관리'},
        ),
        migrations.AlterModelOptions(
            name='supportbusiness',
            options={'verbose_name': '지원사업 관리', 'verbose_name_plural': '지원사업 관리'},
        ),
        migrations.DeleteModel(
            name='FavoriteClipLog',
        ),
        migrations.DeleteModel(
            name='FavoriteCourseLog',
        ),
        migrations.DeleteModel(
            name='FavoritePathLog',
        ),
    ]
