# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-03 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0011_auto_20181002_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='support_business_employee_condition',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hitcliplog',
            name='hit_clip_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
        ),
    ]
