# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0012_auto_20181103_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceservice',
            name='service_file',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='applianceservice',
            name='service_img',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='company_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appliance',
            name='company_keyword',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
