# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0013_auto_20181107_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusiness',
            name='support_business_short_desc',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
