# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0016_auto_20181109_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hit_num', models.IntegerField()),
                ('fav_num', models.IntegerField()),
                ('apply_num', models.IntegerField()),
                ('support_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness')),
            ],
        ),
    ]
