# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-02 16:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0016_auto_20180702_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 2, 16, 39, 56, 464001), null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='file',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
