# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0019_auto_20181117_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPRCountingFilterListTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_filter', models.TextField(blank=True, null=True)),
                ('hit_filter', models.TextField(blank=True, null=True)),
                ('fav_filter', models.TextField(blank=True, null=True)),
                ('applied_filter', models.TextField(blank=True, null=True)),
                ('awarded_filter', models.TextField(blank=True, null=True)),
                ('support_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='OPRCountingStartupListTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_startup_list', models.TextField(blank=True, null=True)),
                ('hit_startup_list', models.TextField(blank=True, null=True)),
                ('fav_startup_list', models.TextField(blank=True, null=True)),
                ('applied_startup_list', models.TextField(blank=True, null=True)),
                ('awarded_startup_list', models.TextField(blank=True, null=True)),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
                ('support_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness')),
            ],
        ),
        migrations.CreateModel(
            name='OPRCountingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hit_num', models.IntegerField()),
                ('fav_num', models.IntegerField()),
                ('apply_num', models.IntegerField()),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
                ('support_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness')),
            ],
        ),
    ]
