# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0020_oprcountingfilterlisttable_oprcountingstartuplisttable_oprcountingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprcountingfilterlisttable',
            name='support_business',
        ),
        migrations.RemoveField(
            model_name='oprcountingtable',
            name='support_business',
        ),
        migrations.AddField(
            model_name='oprcountingfilterlisttable',
            name='opr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
            preserve_default=False,
        ),
    ]
