# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0021_auto_20180702_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverseaInApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nation', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(verbose_name=0)),
            ],
        ),
        migrations.CreateModel(
            name='RevenueInApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeInApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=5, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='facebook_address',
            new_name='sns_address',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='design',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_year_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_year_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='export_before_year_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_3',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_4',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_5',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_6',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_7',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_8',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_9',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_3',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_4',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_5',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_6',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_7',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_8',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_agent_9',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_3',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_4',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_5',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_6',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_7',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_8',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='fund_before_year_9',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='insta_address',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='patent',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='patent_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_year_0',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_year_1',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='revenue_before_year_2',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='trademark',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='website',
        ),
        migrations.AddField(
            model_name='appliance',
            name='business_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='company_intro',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='design_file',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='exp',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appliance',
            name='filter',
            field=models.ManyToManyField(to='supporting_business.Filter'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='homepage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='kind',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='patent_file',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='sub_patent_file',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='trademark_file',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='keyword',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 3, 1, 30, 24, 38001), null=True),
        ),
        migrations.AddField(
            model_name='tradeinapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Appliance'),
        ),
        migrations.AddField(
            model_name='revenueinapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Appliance'),
        ),
        migrations.AddField(
            model_name='overseainapplication',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Appliance'),
        ),
    ]
