# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0021_auto_20181117_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprcountingstartuplisttable',
            name='support_business',
        ),
    ]
