# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0022_remove_oprcountingstartuplisttable_support_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPRINGCountingFilterListTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_filter', models.TextField(blank=True, null=True)),
                ('hit_filter', models.TextField(blank=True, null=True)),
                ('fav_filter', models.TextField(blank=True, null=True)),
                ('applied_filter', models.TextField(blank=True, null=True)),
                ('awarded_filter', models.TextField(blank=True, null=True)),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OPRINGCountingStartupListTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_startup_list', models.TextField(blank=True, null=True)),
                ('hit_startup_list', models.TextField(blank=True, null=True)),
                ('fav_startup_list', models.TextField(blank=True, null=True)),
                ('applied_startup_list', models.TextField(blank=True, null=True)),
                ('awarded_startup_list', models.TextField(blank=True, null=True)),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='OPRINGCountingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hit_num', models.IntegerField()),
                ('fav_num', models.IntegerField()),
                ('apply_num', models.IntegerField()),
                ('opr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.RenameModel(
            old_name='OPRCountingFilterListTable',
            new_name='OPRENDCountingFilterListTable',
        ),
        migrations.RenameModel(
            old_name='OPRCountingStartupListTable',
            new_name='OPRENDCountingStartupListTable',
        ),
        migrations.RenameModel(
            old_name='OPRCountingTable',
            new_name='OPRENDCountingTable',
        ),
    ]
