# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0022_auto_20180703_0130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='sns_address',
            new_name='sns',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 3, 1, 34, 19, 964001), null=True),
        ),
    ]
