# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0023_auto_20180703_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='assurance_employ',
            new_name='assurance_employee',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='hold_employ',
            new_name='hold_employee',
        ),
        migrations.RenameField(
            model_name='appliance',
            old_name='total_employ',
            new_name='total_employee',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 3, 1, 34, 59, 521001), null=True),
        ),
    ]
