# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 01:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0024_auto_20180703_0135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliance',
            old_name='trademark_file',
            new_name='trade_file',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 3, 1, 35, 50, 555001), null=True),
        ),
    ]
