# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-18 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0025_clipcountingtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCountingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_data', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PathCountingTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string_data', models.TextField()),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Path')),
            ],
        ),
    ]
