# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0026_auto_20180704_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='poster',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 4, 18, 9, 6, 148001), null=True),
        ),
    ]
