# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-04 22:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0027_auto_20180704_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='ceremony',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 4, 22, 52, 43, 744200), null=True),
        ),
    ]
