# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0027_auto_20181119_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='all_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='applied_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='awarded_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='fav_filter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit_filter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
