# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0028_auto_20181119_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='all_line_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='applied_line_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='awarded_line_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='fav_line_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit_line_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
