# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0029_auto_20180708_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='interest_startup',
            field=models.ManyToManyField(blank=True, null=True, to='supporting_business.Startup'),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='design_file',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='patent_file',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='sub_patent_file',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='trade_file',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 10, 0, 52, 20, 956000), null=True),
        ),
    ]
