# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 18:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0029_auto_20181119_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportbusiness',
            name='all_filter',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='all_line_data',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='all_startup_list',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='applied_filter',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='applied_line_data',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='applied_startup_list',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='awarded_filter',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='awarded_line_data',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='awarded_startup_list',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='fav_filter',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='fav_line_data',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='fav_startup_list',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='hit_filter',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='hit_line_data',
        ),
        migrations.RemoveField(
            model_name='supportbusiness',
            name='hit_startup_list',
        ),
    ]
