# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-19 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0030_auto_20181119_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='all_filter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='all_line_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='all_startup_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='applied_filter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='applied_line_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='applied_startup_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='awarded_filter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='awarded_line_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='awarded_startup_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='fav_filter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='fav_line_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='fav_startup_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit_filter',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit_line_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='hit_startup_list',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
