# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-20 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0032_auto_20181120_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='support_business_raw_filter_text',
            field=models.CharField(blank=True, default='', max_length=3000, null=True),
        ),
    ]
