# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 16:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0033_auto_20180712_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='thumb',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 12, 16, 26, 42, 858400), null=True),
        ),
    ]
