# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0034_additionaluserinfo_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='support_business_pro_1_check',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='support_business_pro_2_check',
            field=models.BooleanField(default=True),
        ),
    ]
