# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0035_auto_20181124_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='mng_support_business_step_3_etc_input_mojipgenre_chk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='mng_support_business_step_3_etc_input_mojipjogun_chk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='support_business_pro_1_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='support_business_pro_2_check',
            field=models.BooleanField(default=False),
        ),
    ]
