# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0036_auto_20181125_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='is_applied_to_company_info',
            field=models.BooleanField(default=False),
        ),
    ]
