# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 17:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0036_auto_20180712_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='object',
            new_name='rec_dur',
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 12, 17, 43, 30, 164400), null=True),
        ),
    ]
