# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 18:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0037_appliance_is_applied_to_company_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='countingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 792000)),
        ),
        migrations.AddField(
            model_name='countingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 792000)),
        ),
        migrations.AddField(
            model_name='countingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 791000)),
        ),
        migrations.AddField(
            model_name='oprendcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 797000)),
        ),
        migrations.AddField(
            model_name='oprendcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 796000)),
        ),
        migrations.AddField(
            model_name='oprendcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 796000)),
        ),
        migrations.AddField(
            model_name='opringcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 795000)),
        ),
        migrations.AddField(
            model_name='opringcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 794000)),
        ),
        migrations.AddField(
            model_name='opringcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 26, 18, 15, 14, 793000)),
        ),
    ]
