# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-30 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0038_auto_20181126_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 259000)),
        ),
        migrations.AlterField(
            model_name='countingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 258000)),
        ),
        migrations.AlterField(
            model_name='countingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 258000)),
        ),
        migrations.AlterField(
            model_name='oprendcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 261000)),
        ),
        migrations.AlterField(
            model_name='oprendcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 261000)),
        ),
        migrations.AlterField(
            model_name='oprendcountingtable',
            name='apply_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oprendcountingtable',
            name='fav_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oprendcountingtable',
            name='hit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oprendcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 261000)),
        ),
        migrations.AlterField(
            model_name='opringcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 260000)),
        ),
        migrations.AlterField(
            model_name='opringcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 260000)),
        ),
        migrations.AlterField(
            model_name='opringcountingtable',
            name='apply_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opringcountingtable',
            name='fav_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opringcountingtable',
            name='hit_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='opringcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 30, 20, 0, 46, 259000)),
        ),
    ]
