# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-13 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0040_auto_20181130_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaluserinfo',
            name='startup',
        ),
        migrations.AddField(
            model_name='additionaluserinfo',
            name='own_startup',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_startup', to='supporting_business.Startup'),
        ),
        migrations.AlterField(
            model_name='countingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='countingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='countingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 348169)),
        ),
        migrations.AlterField(
            model_name='oprendcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='oprendcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='oprendcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='opringcountingfilterlisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='opringcountingstartuplisttable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
        migrations.AlterField(
            model_name='opringcountingtable',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 13, 10, 13, 50, 350179)),
        ),
    ]
