# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-14 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0043_auto_20180713_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='pick_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appliance',
            name='writing_step',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 14, 9, 42, 27, 281600), null=True),
        ),
    ]
