# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-15 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0045_auto_20180714_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='img',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 15, 18, 4, 25, 737000), null=True),
        ),
    ]
