# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 09:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0048_auto_20180717_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavClipLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FavCourseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FavPathLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('Path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.Path')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo')),
            ],
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 17, 9, 47, 46, 812800), null=True),
        ),
    ]
