# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-17 10:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0049_auto_20180717_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchcliphistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 7, 17, 10, 27, 9, 301800)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchcoursehistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2018, 7, 17, 10, 27, 27, 381800)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchpathhistory',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 17, 10, 26, 58, 796800), null=True),
        ),
    ]
