# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 14:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0053_auto_20180719_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 19, 14, 1, 9, 710000), null=True),
        ),
    ]
