# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-26 20:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0056_auto_20180722_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='sns',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 7, 26, 20, 37, 7, 760000), null=True),
        ),
    ]
