# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 02:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('startup', models.CharField(blank=True, max_length=30, null=True)),
                ('agreement', models.BooleanField(default=True)),
                ('position', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=10, null=True)),
                ('web', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_0', models.CharField(max_length=100)),
                ('cat_1', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, max_length=500, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=5, null=True)),
                ('established_date', models.DateTimeField()),
                ('address', models.CharField(max_length=400)),
                ('website', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SupportBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('from_date', models.DateField()),
                ('end_date', models.DateField()),
                ('target', models.TextField()),
                ('detail', models.TextField()),
                ('apply_method', models.TextField()),
                ('etc', models.TextField()),
                ('filter', models.ManyToManyField(to='supporting_business.Filter')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='startup',
            name='apply',
            field=models.ManyToManyField(to='supporting_business.SupportBusiness'),
        ),
        migrations.AddField(
            model_name='startup',
            name='filter',
            field=models.ManyToManyField(to='supporting_business.Filter'),
        ),
        migrations.AddField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(to='supporting_business.Tag'),
        ),
        migrations.AddField(
            model_name='startup',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
