# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0002_auto_20180213_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='established_date',
            field=models.DateField(),
        ),
    ]
