# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0009_auto_20180219_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='avatar',
            field=models.ImageField(null=True, upload_to='uploads/user/avatar'),
        ),
    ]
