# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0010_additionaluserinfo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='additional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
