# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0011_additionaluserinfo_additional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='additional_email',
            field=models.CharField(blank=True, default='없음', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/avatar'),
        ),
    ]
