# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0014_auto_20180225_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user/company'),
        ),
    ]
