# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-27 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0022_auto_20180228_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
        ),
    ]
