# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0024_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
