# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-01 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0025_appliance_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='business_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='business_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='short_desc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='title_sub',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='title_sub_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='title_tag',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='oversea_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
