# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-03 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0037_auto_20180303_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='etc_file_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='etc_file_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
