# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0044_auto_20180306_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='apply_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
