# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0045_auto_20180306_0150'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=10)),
            ],
        ),
    ]
