# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0046_pagerate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagerate',
            name='rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pagerate',
            name='page',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pagerate',
            name='user',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
