# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0047_auto_20180306_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='auth',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='uploads/user/avatar'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='belong_to',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='category',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='department',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='position',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='startup',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='tel',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='web',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='address',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='startup',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='startup',
            name='desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='startup',
            name='employee_number',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='established_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_status',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='service_products',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='short_desc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='website',
            field=models.CharField(default='', max_length=300),
        ),
    ]
