# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0055_supportbusiness_due_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='interest',
            field=models.ManyToManyField(blank=True, null=True, to='supporting_business.SupportBusiness'),
        ),
    ]
