# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0056_auto_20180312_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='filter',
            field=models.ManyToManyField(blank=True, null=True, to='supporting_business.Filter'),
        ),
        migrations.AlterField(
            model_name='startup',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='supporting_business.Tag'),
        ),
    ]
