# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0058_auto_20180313_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarm',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
