# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0063_auto_20180314_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_0',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_3',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_4',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_5',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_6',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_7',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_8',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='fund_before_agent_9',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supportbusiness',
            name='etc_file_title',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
