# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-18 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0066_auto_20180318_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startup',
            name='export_before_year_0',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='export_before_year_1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='export_before_year_2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_0',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_1',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_2',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_3',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_4',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_5',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_6',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_7',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_8',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='fund_before_year_9',
            field=models.CharField(blank=True, default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='revenue_before_year_0',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='revenue_before_year_1',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='revenue_before_year_2',
            field=models.CharField(blank=True, default='', max_length=5, null=True),
        ),
    ]
