# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-19 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0068_auto_20180319_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='confirm',
            field=models.BooleanField(default=True),
        ),
    ]
