# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-24 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0076_auto_20180324_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 3, 24, 13, 21, 26, 569414), null=True),
        ),
    ]
