# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 04:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0077_auto_20180324_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportbusiness',
            name='relate_sb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.SupportBusiness'),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 3, 28, 4, 31, 25, 638800), null=True),
        ),
    ]
