# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0082_auto_20180406_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 6, 16, 49, 59, 167403), null=True),
        ),
    ]
