# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 16:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0083_auto_20180406_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 6, 16, 59, 27, 775403), null=True),
        ),
    ]
