# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0085_auto_20180407_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionaluserinfo',
            name='parent',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='supporting_business.AdditionalUserInfo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supportbusiness',
            name='confirm_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='confirm_user', to='supporting_business.AdditionalUserInfo'),
        ),
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 10, 10, 13, 4, 939011), null=True),
        ),
    ]
