# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporting_business', '0089_auto_20180410_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitlog',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2018, 4, 10, 16, 10, 22, 704011), null=True),
        ),
    ]
